-- 1. Buat Tabel Produk
CREATE TABLE IF NOT EXISTS public.produk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    harga INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Insert Contoh Data
INSERT INTO public.produk (nama, harga) VALUES
('Espresso Single Origin', 18000),
('Kopi Susu Gula Aren', 22000),
('Americano Ice/Hot', 20000),
('Matcha Latte Cream', 25000),
('Chocolate Ice Blend', 23000),
('Croissant Butter', 15000);

-- 3. Tabel Transaksi / Pesanan
CREATE TABLE IF NOT EXISTS public.transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_harga INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Detail Transaksi
CREATE TABLE IF NOT EXISTS public.detail_transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_id BIGINT REFERENCES public.transaksi(id) ON DELETE CASCADE,
    produk_id BIGINT REFERENCES public.produk(id),
    jumlah INT NOT NULL,
    subtotal INT NOT NULL
);


